version: "3.9"
services:
  reservation-api:
    build: .
    restart: always
    volumes:
      - type: volume
        source: local-env_shared
        target: /home
    ports:
      - 8085:8085
    environment:
      - USER_API_GRPC_ADDRESS=user-api

networks:
  default:
    name: local-env_default

volumes:
  local-env_shared:
    external: true